name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - 1.61
          - stable
          - nightly
        features:
          -
          - --no-default-features
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release ${{ matrix.features }}
      - run: cargo doc --release ${{ matrix.features }}