name: CI-version

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
        features:
          -
          - --features micro-qr
          - --features rmqr
          - --features url
          - --features kanji
          - --features async-write
          - --no-default-features
          - --no-default-features --features qr
          - --no-default-features --features micro-qr
          - --no-default-features --features qr --features micro-qr
          - --no-default-features --features rmqr
          - --no-default-features --features qr --features kanji
          - --all-features
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release ${{ matrix.features }}
      - run: cargo doc --release ${{ matrix.features }}

  MSRV:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - 1.89
        features:
          -
          - --features micro-qr
          - --features rmqr
          - --features url
          - --features kanji
          - --features async-write
          - --no-default-features
          - --no-default-features --features qr
          - --no-default-features --features micro-qr
          - --no-default-features --features qr --features micro-qr
          - --no-default-features --features rmqr
          - --no-default-features --features qr --features kanji
          - --all-features
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }} (${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --release --lib --bins ${{ matrix.features }}